FROM tomcat:8
MAINTAINER Sherri Conrod <devopsontap@yahoo.com>
#your image name
#update your docker image with your required python modules and other libraries - remember to manuall increment the tag version until symantec verioning is applied
#Required to use your params file for your docker repo with creds - enter into vault too.

ENV CENTOS_FRONTEND noninteractive




COPY ./context.xml /opt/tomcat/webapps/manager/META-INF/context.xml
COPY ./tomcat-users.xml /opt/tomcat/conf/tomcat-users.xml
COPY ./tomcat.service /etc/systemd/system/tomcat.service
COPY ./Supercar-Trader.war /opt/tomcat/webapps/


EXPOSE 80
ENV HOME /root
CMD ["systemctl start tomcat"]






