jobs:
- name: build-and-push
  plan:
  - get: git-dockerfile-resource
  - config:
      image_resource:
        name: ""
        source:
          repository: concourse/oci-build-task
        type: registry-image
      inputs:
      - name: git-dockerfile-resource
      outputs:
      - name: image
      params:
        CONTEXT: git-dockerfile-resource
      platform: linux
      run:
        path: build
    privileged: true
    task: build-task-image
  - params:
      image: image/image.tar
    put: python-aws-image
resources:
- icon: github
  name: git-dockerfile-resource
  source:
    Username: sconrod-tester
    branch: python-aws
    email: ((email))
    private_key: ((private_key))
    uri: git@github.com:sconrod-tester/docker-builds.git
  type: git
- icon: docker
  name: python-aws-image
  source:
    password: ((registry-password))!
    repository: sconrod/python-aws-image
    tag: latest
    username: ((registry-username))
  type: registry-image
